# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
